# TCL File Generated by Component Editor 25.1
# Tue Mar 31 02:54:30 EDT 2026
# DO NOT MODIFY


# 
# logic_analyzer "Logic_Analyzer" v1.0
#  2026.03.31.02:54:30
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module logic_analyzer
# 
set_module_property DESCRIPTION ""
set_module_property NAME logic_analyzer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Logic_Analyzer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL logic_analyzer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file logic_analyzer.sv SYSTEM_VERILOG PATH ../src/Logic_Analyzer/logic_analyzer.sv TOP_LEVEL_FILE
add_fileset_file signal_capture.sv SYSTEM_VERILOG PATH ../src/Logic_Analyzer/signal_capture.sv
add_fileset_file signal_generator.sv SYSTEM_VERILOG PATH ../src/Logic_Analyzer/signal_generator.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset nreset reset_n Input 1


# 
# connection point channels
# 
add_interface channels conduit end
set_interface_property channels associatedClock clock
set_interface_property channels associatedReset ""
set_interface_property channels ENABLED true
set_interface_property channels EXPORT_OF ""
set_interface_property channels PORT_NAME_MAP ""
set_interface_property channels CMSIS_SVD_VARIABLES ""
set_interface_property channels SVD_ADDRESS_GROUP ""

add_interface_port channels OUT_CH data_out Output 16
add_interface_port channels IN_CH data_in Input 16


# 
# connection point avalon_la_slave
# 
add_interface avalon_la_slave avalon end
set_interface_property avalon_la_slave addressUnits WORDS
set_interface_property avalon_la_slave associatedClock clock
set_interface_property avalon_la_slave associatedReset reset
set_interface_property avalon_la_slave bitsPerSymbol 8
set_interface_property avalon_la_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_la_slave burstcountUnits WORDS
set_interface_property avalon_la_slave explicitAddressSpan 32
set_interface_property avalon_la_slave holdTime 0
set_interface_property avalon_la_slave linewrapBursts false
set_interface_property avalon_la_slave maximumPendingReadTransactions 0
set_interface_property avalon_la_slave maximumPendingWriteTransactions 0
set_interface_property avalon_la_slave readLatency 0
set_interface_property avalon_la_slave readWaitTime 1
set_interface_property avalon_la_slave setupTime 0
set_interface_property avalon_la_slave timingUnits Cycles
set_interface_property avalon_la_slave writeWaitStates 1
set_interface_property avalon_la_slave writeWaitTime 1
set_interface_property avalon_la_slave ENABLED true
set_interface_property avalon_la_slave EXPORT_OF ""
set_interface_property avalon_la_slave PORT_NAME_MAP ""
set_interface_property avalon_la_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_la_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_la_slave address address Input 3
add_interface_port avalon_la_slave write write Input 1
add_interface_port avalon_la_slave writedata writedata Input 32
add_interface_port avalon_la_slave read read Input 1
add_interface_port avalon_la_slave chipselect chipselect Input 1
add_interface_port avalon_la_slave readdata readdata Output 32
set_interface_assignment avalon_la_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_la_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_la_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_la_slave embeddedsw.configuration.isPrintableDevice 0

