/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'NiosVg' in SOPC Builder design 'Computer_System'
 * SOPC Builder design path: /home/wavius/Documents/GitHub/Logic-Analyzer/Computer_Systems/DE1-SoC/out/DE1_SoC_NiosVg_Computer/Computer_System.sopcinfo
 *
 * Generated: Fri Mar 20 03:56:56 EDT 2026
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * ADC configuration
 *
 */

#define ADC_BASE 0xff204000
#define ADC_IRQ -1
#define ADC_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ADC_NAME "/dev/ADC"
#define ADC_SPAN 32
#define ADC_TYPE "altera_up_avalon_adc"
#define ALT_MODULE_CLASS_ADC altera_up_avalon_adc


/*
 * AV_Config configuration
 *
 */

#define ALT_MODULE_CLASS_AV_Config altera_up_avalon_audio_and_video_config
#define AV_CONFIG_BASE 0xff203000
#define AV_CONFIG_IRQ -1
#define AV_CONFIG_IRQ_INTERRUPT_CONTROLLER_ID -1
#define AV_CONFIG_NAME "/dev/AV_Config"
#define AV_CONFIG_SPAN 16
#define AV_CONFIG_TYPE "altera_up_avalon_audio_and_video_config"


/*
 * Audio_Subsystem_Audio configuration
 *
 */

#define ALT_MODULE_CLASS_Audio_Subsystem_Audio altera_up_avalon_audio
#define AUDIO_SUBSYSTEM_AUDIO_BASE 0xff203040
#define AUDIO_SUBSYSTEM_AUDIO_IRQ 5
#define AUDIO_SUBSYSTEM_AUDIO_IRQ_INTERRUPT_CONTROLLER_ID 0
#define AUDIO_SUBSYSTEM_AUDIO_NAME "/dev/Audio_Subsystem_Audio"
#define AUDIO_SUBSYSTEM_AUDIO_SPAN 16
#define AUDIO_SUBSYSTEM_AUDIO_TYPE "altera_up_avalon_audio"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "intel_niosv_g"
#define ALT_CPU_CLIC_EN 0
#define ALT_CPU_CPU_FREQ 100000000u
#define ALT_CPU_DATA_ADDR_WIDTH 0x20
#define ALT_CPU_DCACHE_LINE_SIZE 32
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_DCACHE_SIZE 1024
#define ALT_CPU_FREQ 100000000
#define ALT_CPU_HAS_CSR_SUPPORT 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 1024
#define ALT_CPU_INST_ADDR_WIDTH 0x20
#define ALT_CPU_INT_MODE 0
#define ALT_CPU_MTIME_OFFSET 0xff202100
#define ALT_CPU_NAME "NiosVg"
#define ALT_CPU_NIOSV_CORE_VARIANT 3
#define ALT_CPU_NUM_GPR 32
#define ALT_CPU_NUM_SRF_BANKS 1
#define ALT_CPU_RESET_ADDR 0x00000000
#define ALT_CPU_TICKS_PER_SEC NIOSV_INTERNAL_TIMER_TICKS_PER_SECOND
#define ALT_CPU_TIMER_DEVICE_TYPE 2


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define BANTAMLAKE_CLIC_EN 0
#define BANTAMLAKE_CPU_FREQ 100000000u
#define BANTAMLAKE_DATA_ADDR_WIDTH 0x20
#define BANTAMLAKE_DCACHE_LINE_SIZE 32
#define BANTAMLAKE_DCACHE_LINE_SIZE_LOG2 5
#define BANTAMLAKE_DCACHE_SIZE 1024
#define BANTAMLAKE_HAS_CSR_SUPPORT 1
#define BANTAMLAKE_HAS_DEBUG_STUB
#define BANTAMLAKE_ICACHE_LINE_SIZE 32
#define BANTAMLAKE_ICACHE_LINE_SIZE_LOG2 5
#define BANTAMLAKE_ICACHE_SIZE 1024
#define BANTAMLAKE_INST_ADDR_WIDTH 0x20
#define BANTAMLAKE_INT_MODE 0
#define BANTAMLAKE_MTIME_OFFSET 0xff202100
#define BANTAMLAKE_NIOSV_CORE_VARIANT 3
#define BANTAMLAKE_NUM_GPR 32
#define BANTAMLAKE_NUM_SRF_BANKS 1
#define BANTAMLAKE_RESET_ADDR 0x00000000
#define BANTAMLAKE_TICKS_PER_SEC NIOSV_INTERNAL_TIMER_TICKS_PER_SECOND
#define BANTAMLAKE_TIMER_DEVICE_TYPE 2


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_UP_AVALON_ADC
#define __ALTERA_UP_AVALON_AUDIO
#define __ALTERA_UP_AVALON_AUDIO_AND_VIDEO_CONFIG
#define __ALTERA_UP_AVALON_IRDA
#define __ALTERA_UP_AVALON_PS2
#define __ALTERA_UP_AVALON_VIDEO_DMA_CONTROLLER
#define __ALTERA_UP_AVALON_VIDEO_RGB_RESAMPLER
#define __INTEL_NIOSV_G
#define __LOGIC_ANALYZER
#define __SDRAM_64MB


/*
 * Expansion_JP1 configuration
 *
 */

#define ALT_MODULE_CLASS_Expansion_JP1 altera_avalon_pio
#define EXPANSION_JP1_BASE 0xff200060
#define EXPANSION_JP1_BIT_CLEARING_EDGE_REGISTER 1
#define EXPANSION_JP1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define EXPANSION_JP1_CAPTURE 1
#define EXPANSION_JP1_DATA_WIDTH 32
#define EXPANSION_JP1_DO_TEST_BENCH_WIRING 1
#define EXPANSION_JP1_DRIVEN_SIM_VALUE 0
#define EXPANSION_JP1_EDGE_TYPE "FALLING"
#define EXPANSION_JP1_FREQ 100000000
#define EXPANSION_JP1_HAS_IN 0
#define EXPANSION_JP1_HAS_OUT 0
#define EXPANSION_JP1_HAS_TRI 1
#define EXPANSION_JP1_IRQ 11
#define EXPANSION_JP1_IRQ_INTERRUPT_CONTROLLER_ID 0
#define EXPANSION_JP1_IRQ_TYPE "EDGE"
#define EXPANSION_JP1_NAME "/dev/Expansion_JP1"
#define EXPANSION_JP1_RESET_VALUE 0
#define EXPANSION_JP1_SPAN 16
#define EXPANSION_JP1_TYPE "altera_avalon_pio"


/*
 * Expansion_JP2 configuration
 *
 */

#define ALT_MODULE_CLASS_Expansion_JP2 altera_avalon_pio
#define EXPANSION_JP2_BASE 0xff200070
#define EXPANSION_JP2_BIT_CLEARING_EDGE_REGISTER 1
#define EXPANSION_JP2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define EXPANSION_JP2_CAPTURE 1
#define EXPANSION_JP2_DATA_WIDTH 32
#define EXPANSION_JP2_DO_TEST_BENCH_WIRING 1
#define EXPANSION_JP2_DRIVEN_SIM_VALUE 0
#define EXPANSION_JP2_EDGE_TYPE "FALLING"
#define EXPANSION_JP2_FREQ 100000000
#define EXPANSION_JP2_HAS_IN 0
#define EXPANSION_JP2_HAS_OUT 0
#define EXPANSION_JP2_HAS_TRI 1
#define EXPANSION_JP2_IRQ 12
#define EXPANSION_JP2_IRQ_INTERRUPT_CONTROLLER_ID 0
#define EXPANSION_JP2_IRQ_TYPE "EDGE"
#define EXPANSION_JP2_NAME "/dev/Expansion_JP2"
#define EXPANSION_JP2_RESET_VALUE 0
#define EXPANSION_JP2_SPAN 16
#define EXPANSION_JP2_TYPE "altera_avalon_pio"


/*
 * HEX3_HEX0 configuration
 *
 */

#define ALT_MODULE_CLASS_HEX3_HEX0 altera_avalon_pio
#define HEX3_HEX0_BASE 0xff200020
#define HEX3_HEX0_BIT_CLEARING_EDGE_REGISTER 0
#define HEX3_HEX0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HEX3_HEX0_CAPTURE 0
#define HEX3_HEX0_DATA_WIDTH 32
#define HEX3_HEX0_DO_TEST_BENCH_WIRING 0
#define HEX3_HEX0_DRIVEN_SIM_VALUE 0
#define HEX3_HEX0_EDGE_TYPE "NONE"
#define HEX3_HEX0_FREQ 100000000
#define HEX3_HEX0_HAS_IN 0
#define HEX3_HEX0_HAS_OUT 1
#define HEX3_HEX0_HAS_TRI 0
#define HEX3_HEX0_IRQ -1
#define HEX3_HEX0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define HEX3_HEX0_IRQ_TYPE "NONE"
#define HEX3_HEX0_NAME "/dev/HEX3_HEX0"
#define HEX3_HEX0_RESET_VALUE 0
#define HEX3_HEX0_SPAN 16
#define HEX3_HEX0_TYPE "altera_avalon_pio"


/*
 * HEX5_HEX4 configuration
 *
 */

#define ALT_MODULE_CLASS_HEX5_HEX4 altera_avalon_pio
#define HEX5_HEX4_BASE 0xff200030
#define HEX5_HEX4_BIT_CLEARING_EDGE_REGISTER 0
#define HEX5_HEX4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HEX5_HEX4_CAPTURE 0
#define HEX5_HEX4_DATA_WIDTH 16
#define HEX5_HEX4_DO_TEST_BENCH_WIRING 0
#define HEX5_HEX4_DRIVEN_SIM_VALUE 0
#define HEX5_HEX4_EDGE_TYPE "NONE"
#define HEX5_HEX4_FREQ 100000000
#define HEX5_HEX4_HAS_IN 0
#define HEX5_HEX4_HAS_OUT 1
#define HEX5_HEX4_HAS_TRI 0
#define HEX5_HEX4_IRQ -1
#define HEX5_HEX4_IRQ_INTERRUPT_CONTROLLER_ID -1
#define HEX5_HEX4_IRQ_TYPE "NONE"
#define HEX5_HEX4_NAME "/dev/HEX5_HEX4"
#define HEX5_HEX4_RESET_VALUE 0
#define HEX5_HEX4_SPAN 16
#define HEX5_HEX4_TYPE "altera_avalon_pio"


/*
 * Interval_Timer_NiosV configuration
 *
 */

#define ALT_MODULE_CLASS_Interval_Timer_NiosV altera_avalon_timer
#define INTERVAL_TIMER_NIOSV_ALWAYS_RUN 0
#define INTERVAL_TIMER_NIOSV_BASE 0xff202000
#define INTERVAL_TIMER_NIOSV_COUNTER_SIZE 32
#define INTERVAL_TIMER_NIOSV_FIXED_PERIOD 0
#define INTERVAL_TIMER_NIOSV_FREQ 100000000
#define INTERVAL_TIMER_NIOSV_IRQ 0
#define INTERVAL_TIMER_NIOSV_IRQ_INTERRUPT_CONTROLLER_ID 0
#define INTERVAL_TIMER_NIOSV_LOAD_VALUE 12499999
#define INTERVAL_TIMER_NIOSV_MULT 0.001
#define INTERVAL_TIMER_NIOSV_NAME "/dev/Interval_Timer_NiosV"
#define INTERVAL_TIMER_NIOSV_PERIOD 125.0
#define INTERVAL_TIMER_NIOSV_PERIOD_UNITS "ms"
#define INTERVAL_TIMER_NIOSV_RESET_OUTPUT 0
#define INTERVAL_TIMER_NIOSV_SNAPSHOT 1
#define INTERVAL_TIMER_NIOSV_SPAN 32
#define INTERVAL_TIMER_NIOSV_TICKS_PER_SEC 8
#define INTERVAL_TIMER_NIOSV_TIMEOUT_PULSE_OUTPUT 0
#define INTERVAL_TIMER_NIOSV_TIMER_DEVICE_TYPE 1
#define INTERVAL_TIMER_NIOSV_TYPE "altera_avalon_timer"


/*
 * Interval_Timer_NiosV_2 configuration
 *
 */

#define ALT_MODULE_CLASS_Interval_Timer_NiosV_2 altera_avalon_timer
#define INTERVAL_TIMER_NIOSV_2_ALWAYS_RUN 0
#define INTERVAL_TIMER_NIOSV_2_BASE 0xff202020
#define INTERVAL_TIMER_NIOSV_2_COUNTER_SIZE 32
#define INTERVAL_TIMER_NIOSV_2_FIXED_PERIOD 0
#define INTERVAL_TIMER_NIOSV_2_FREQ 100000000
#define INTERVAL_TIMER_NIOSV_2_IRQ 1
#define INTERVAL_TIMER_NIOSV_2_IRQ_INTERRUPT_CONTROLLER_ID 0
#define INTERVAL_TIMER_NIOSV_2_LOAD_VALUE 12499999
#define INTERVAL_TIMER_NIOSV_2_MULT 0.001
#define INTERVAL_TIMER_NIOSV_2_NAME "/dev/Interval_Timer_NiosV_2"
#define INTERVAL_TIMER_NIOSV_2_PERIOD 125.0
#define INTERVAL_TIMER_NIOSV_2_PERIOD_UNITS "ms"
#define INTERVAL_TIMER_NIOSV_2_RESET_OUTPUT 0
#define INTERVAL_TIMER_NIOSV_2_SNAPSHOT 1
#define INTERVAL_TIMER_NIOSV_2_SPAN 32
#define INTERVAL_TIMER_NIOSV_2_TICKS_PER_SEC 8
#define INTERVAL_TIMER_NIOSV_2_TIMEOUT_PULSE_OUTPUT 0
#define INTERVAL_TIMER_NIOSV_2_TIMER_DEVICE_TYPE 1
#define INTERVAL_TIMER_NIOSV_2_TYPE "altera_avalon_timer"


/*
 * IrDA configuration
 *
 */

#define ALT_MODULE_CLASS_IrDA altera_up_avalon_irda
#define IRDA_BASE 0xff201020
#define IRDA_IRQ 9
#define IRDA_IRQ_INTERRUPT_CONTROLLER_ID 0
#define IRDA_NAME "/dev/IrDA"
#define IRDA_SPAN 8
#define IRDA_TYPE "altera_up_avalon_irda"


/*
 * JTAG_UART_NiosV configuration
 *
 */

#define ALT_MODULE_CLASS_JTAG_UART_NiosV altera_avalon_jtag_uart
#define JTAG_UART_NIOSV_BASE 0xff201000
#define JTAG_UART_NIOSV_IRQ 8
#define JTAG_UART_NIOSV_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NIOSV_NAME "/dev/JTAG_UART_NiosV"
#define JTAG_UART_NIOSV_READ_DEPTH 64
#define JTAG_UART_NIOSV_READ_THRESHOLD 8
#define JTAG_UART_NIOSV_SPAN 8
#define JTAG_UART_NIOSV_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_NIOSV_WRITE_DEPTH 64
#define JTAG_UART_NIOSV_WRITE_THRESHOLD 8


/*
 * LEDs configuration
 *
 */

#define ALT_MODULE_CLASS_LEDs altera_avalon_pio
#define LEDS_BASE 0xff200000
#define LEDS_BIT_CLEARING_EDGE_REGISTER 0
#define LEDS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LEDS_CAPTURE 0
#define LEDS_DATA_WIDTH 10
#define LEDS_DO_TEST_BENCH_WIRING 0
#define LEDS_DRIVEN_SIM_VALUE 0
#define LEDS_EDGE_TYPE "NONE"
#define LEDS_FREQ 100000000
#define LEDS_HAS_IN 0
#define LEDS_HAS_OUT 1
#define LEDS_HAS_TRI 0
#define LEDS_IRQ -1
#define LEDS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDS_IRQ_TYPE "NONE"
#define LEDS_NAME "/dev/LEDs"
#define LEDS_RESET_VALUE 0
#define LEDS_SPAN 16
#define LEDS_TYPE "altera_avalon_pio"


/*
 * Logic_Analyzer_0 configuration
 *
 */

#define ALT_MODULE_CLASS_Logic_Analyzer_0 Logic_Analyzer
#define LOGIC_ANALYZER_0_BASE 0xff205000
#define LOGIC_ANALYZER_0_IRQ -1
#define LOGIC_ANALYZER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LOGIC_ANALYZER_0_NAME "/dev/Logic_Analyzer_0"
#define LOGIC_ANALYZER_0_SPAN 32
#define LOGIC_ANALYZER_0_TYPE "Logic_Analyzer"


/*
 * NiosVg_dm_agent configuration
 *
 */

#define ALT_MODULE_CLASS_NiosVg_dm_agent intel_niosv_g
#define NIOSVG_DM_AGENT_BASE 0xa000000
#define NIOSVG_DM_AGENT_CLIC_EN 0
#define NIOSVG_DM_AGENT_CPU_FREQ 100000000u
#define NIOSVG_DM_AGENT_DATA_ADDR_WIDTH 0x20
#define NIOSVG_DM_AGENT_DCACHE_LINE_SIZE 32
#define NIOSVG_DM_AGENT_DCACHE_LINE_SIZE_LOG2 5
#define NIOSVG_DM_AGENT_DCACHE_SIZE 1024
#define NIOSVG_DM_AGENT_HAS_CSR_SUPPORT 1
#define NIOSVG_DM_AGENT_HAS_DEBUG_STUB
#define NIOSVG_DM_AGENT_ICACHE_LINE_SIZE 32
#define NIOSVG_DM_AGENT_ICACHE_LINE_SIZE_LOG2 5
#define NIOSVG_DM_AGENT_ICACHE_SIZE 1024
#define NIOSVG_DM_AGENT_INST_ADDR_WIDTH 0x20
#define NIOSVG_DM_AGENT_INTERRUPT_CONTROLLER_ID 0
#define NIOSVG_DM_AGENT_INT_MODE 0
#define NIOSVG_DM_AGENT_IRQ -1
#define NIOSVG_DM_AGENT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define NIOSVG_DM_AGENT_MTIME_OFFSET 0xff202100
#define NIOSVG_DM_AGENT_NAME "/dev/NiosVg_dm_agent"
#define NIOSVG_DM_AGENT_NIOSV_CORE_VARIANT 3
#define NIOSVG_DM_AGENT_NUM_GPR 32
#define NIOSVG_DM_AGENT_NUM_SRF_BANKS 1
#define NIOSVG_DM_AGENT_RESET_ADDR 0x00000000
#define NIOSVG_DM_AGENT_SPAN 65536
#define NIOSVG_DM_AGENT_TICKS_PER_SEC NIOSV_INTERNAL_TIMER_TICKS_PER_SECOND
#define NIOSVG_DM_AGENT_TIMER_DEVICE_TYPE 2
#define NIOSVG_DM_AGENT_TYPE "intel_niosv_g"


/*
 * NiosVg_timer_sw_agent configuration
 *
 */

#define ALT_MODULE_CLASS_NiosVg_timer_sw_agent intel_niosv_g
#define NIOSVG_TIMER_SW_AGENT_BASE 0xff202100
#define NIOSVG_TIMER_SW_AGENT_CLIC_EN 0
#define NIOSVG_TIMER_SW_AGENT_CPU_FREQ 100000000u
#define NIOSVG_TIMER_SW_AGENT_DATA_ADDR_WIDTH 0x20
#define NIOSVG_TIMER_SW_AGENT_DCACHE_LINE_SIZE 32
#define NIOSVG_TIMER_SW_AGENT_DCACHE_LINE_SIZE_LOG2 5
#define NIOSVG_TIMER_SW_AGENT_DCACHE_SIZE 1024
#define NIOSVG_TIMER_SW_AGENT_HAS_CSR_SUPPORT 1
#define NIOSVG_TIMER_SW_AGENT_HAS_DEBUG_STUB
#define NIOSVG_TIMER_SW_AGENT_ICACHE_LINE_SIZE 32
#define NIOSVG_TIMER_SW_AGENT_ICACHE_LINE_SIZE_LOG2 5
#define NIOSVG_TIMER_SW_AGENT_ICACHE_SIZE 1024
#define NIOSVG_TIMER_SW_AGENT_INST_ADDR_WIDTH 0x20
#define NIOSVG_TIMER_SW_AGENT_INTERRUPT_CONTROLLER_ID 0
#define NIOSVG_TIMER_SW_AGENT_INT_MODE 0
#define NIOSVG_TIMER_SW_AGENT_IRQ -1
#define NIOSVG_TIMER_SW_AGENT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define NIOSVG_TIMER_SW_AGENT_MTIME_OFFSET 0xff202100
#define NIOSVG_TIMER_SW_AGENT_NAME "/dev/NiosVg_timer_sw_agent"
#define NIOSVG_TIMER_SW_AGENT_NIOSV_CORE_VARIANT 3
#define NIOSVG_TIMER_SW_AGENT_NUM_GPR 32
#define NIOSVG_TIMER_SW_AGENT_NUM_SRF_BANKS 1
#define NIOSVG_TIMER_SW_AGENT_RESET_ADDR 0x00000000
#define NIOSVG_TIMER_SW_AGENT_SPAN 64
#define NIOSVG_TIMER_SW_AGENT_TICKS_PER_SEC NIOSV_INTERNAL_TIMER_TICKS_PER_SECOND
#define NIOSVG_TIMER_SW_AGENT_TIMER_DEVICE_TYPE 2
#define NIOSVG_TIMER_SW_AGENT_TYPE "intel_niosv_g"


/*
 * Onchip_SRAM configuration
 *
 */

#define ALT_MODULE_CLASS_Onchip_SRAM altera_avalon_onchip_memory2
#define ONCHIP_SRAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_SRAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_SRAM_BASE 0x8000000
#define ONCHIP_SRAM_CONTENTS_INFO ""
#define ONCHIP_SRAM_DUAL_PORT 1
#define ONCHIP_SRAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_SRAM_INIT_CONTENTS_FILE "Computer_System_Onchip_SRAM"
#define ONCHIP_SRAM_INIT_MEM_CONTENT 1
#define ONCHIP_SRAM_INSTANCE_ID "NONE"
#define ONCHIP_SRAM_IRQ -1
#define ONCHIP_SRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_SRAM_NAME "/dev/Onchip_SRAM"
#define ONCHIP_SRAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_SRAM_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_SRAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_SRAM_SINGLE_CLOCK_OP 1
#define ONCHIP_SRAM_SIZE_MULTIPLE 1
#define ONCHIP_SRAM_SIZE_VALUE 262144
#define ONCHIP_SRAM_SPAN 262144
#define ONCHIP_SRAM_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_SRAM_WRITABLE 1


/*
 * PS2_Port configuration
 *
 */

#define ALT_MODULE_CLASS_PS2_Port altera_up_avalon_ps2
#define PS2_PORT_BASE 0xff200100
#define PS2_PORT_IRQ 6
#define PS2_PORT_IRQ_INTERRUPT_CONTROLLER_ID 0
#define PS2_PORT_NAME "/dev/PS2_Port"
#define PS2_PORT_SPAN 8
#define PS2_PORT_TYPE "altera_up_avalon_ps2"


/*
 * PS2_Port_Dual configuration
 *
 */

#define ALT_MODULE_CLASS_PS2_Port_Dual altera_up_avalon_ps2
#define PS2_PORT_DUAL_BASE 0xff200108
#define PS2_PORT_DUAL_IRQ 7
#define PS2_PORT_DUAL_IRQ_INTERRUPT_CONTROLLER_ID 0
#define PS2_PORT_DUAL_NAME "/dev/PS2_Port_Dual"
#define PS2_PORT_DUAL_SPAN 8
#define PS2_PORT_DUAL_TYPE "altera_up_avalon_ps2"


/*
 * Pushbuttons configuration
 *
 */

#define ALT_MODULE_CLASS_Pushbuttons altera_avalon_pio
#define PUSHBUTTONS_BASE 0xff200050
#define PUSHBUTTONS_BIT_CLEARING_EDGE_REGISTER 1
#define PUSHBUTTONS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PUSHBUTTONS_CAPTURE 1
#define PUSHBUTTONS_DATA_WIDTH 4
#define PUSHBUTTONS_DO_TEST_BENCH_WIRING 1
#define PUSHBUTTONS_DRIVEN_SIM_VALUE 0
#define PUSHBUTTONS_EDGE_TYPE "FALLING"
#define PUSHBUTTONS_FREQ 100000000
#define PUSHBUTTONS_HAS_IN 1
#define PUSHBUTTONS_HAS_OUT 0
#define PUSHBUTTONS_HAS_TRI 0
#define PUSHBUTTONS_IRQ 2
#define PUSHBUTTONS_IRQ_INTERRUPT_CONTROLLER_ID 0
#define PUSHBUTTONS_IRQ_TYPE "EDGE"
#define PUSHBUTTONS_NAME "/dev/Pushbuttons"
#define PUSHBUTTONS_RESET_VALUE 0
#define PUSHBUTTONS_SPAN 16
#define PUSHBUTTONS_TYPE "altera_avalon_pio"


/*
 * SDRAM configuration
 *
 */

#define ALT_MODULE_CLASS_SDRAM sdram_64mb
#define SDRAM_BASE 0x0
#define SDRAM_IRQ -1
#define SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_NAME "/dev/SDRAM"
#define SDRAM_SPAN 67108864
#define SDRAM_TYPE "sdram_64mb"


/*
 * Slider_Switches configuration
 *
 */

#define ALT_MODULE_CLASS_Slider_Switches altera_avalon_pio
#define SLIDER_SWITCHES_BASE 0xff200040
#define SLIDER_SWITCHES_BIT_CLEARING_EDGE_REGISTER 0
#define SLIDER_SWITCHES_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SLIDER_SWITCHES_CAPTURE 0
#define SLIDER_SWITCHES_DATA_WIDTH 10
#define SLIDER_SWITCHES_DO_TEST_BENCH_WIRING 1
#define SLIDER_SWITCHES_DRIVEN_SIM_VALUE 0
#define SLIDER_SWITCHES_EDGE_TYPE "NONE"
#define SLIDER_SWITCHES_FREQ 100000000
#define SLIDER_SWITCHES_HAS_IN 1
#define SLIDER_SWITCHES_HAS_OUT 0
#define SLIDER_SWITCHES_HAS_TRI 0
#define SLIDER_SWITCHES_IRQ -1
#define SLIDER_SWITCHES_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SLIDER_SWITCHES_IRQ_TYPE "NONE"
#define SLIDER_SWITCHES_NAME "/dev/Slider_Switches"
#define SLIDER_SWITCHES_RESET_VALUE 0
#define SLIDER_SWITCHES_SPAN 16
#define SLIDER_SWITCHES_TYPE "altera_avalon_pio"


/*
 * SysID configuration
 *
 */

#define ALT_MODULE_CLASS_SysID altera_avalon_sysid_qsys
#define SYSID_BASE 0xff202040
#define SYSID_ID 0
#define SYSID_IRQ -1
#define SYSID_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_NAME "/dev/SysID"
#define SYSID_SPAN 8
#define SYSID_TIMESTAMP 1773975723
#define SYSID_TYPE "altera_avalon_sysid_qsys"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone V"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/JTAG_UART_NiosV"
#define ALT_STDERR_BASE 0xff201000
#define ALT_STDERR_DEV JTAG_UART_NiosV
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/JTAG_UART_NiosV"
#define ALT_STDIN_BASE 0xff201000
#define ALT_STDIN_DEV JTAG_UART_NiosV
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/JTAG_UART_NiosV"
#define ALT_STDOUT_BASE 0xff201000
#define ALT_STDOUT_DEV JTAG_UART_NiosV
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSID_BASE SYSID_BASE
#define ALT_SYSID_ID SYSID_ID
#define ALT_SYSTEM_NAME "Computer_System"
#define ALT_SYS_CLK_TICKS_PER_SEC ALT_CPU_TICKS_PER_SEC
#define ALT_TIMESTAMP_CLK_TIMER_DEVICE_TYPE ALT_CPU_TIMER_DEVICE_TYPE


/*
 * VGA_Subsystem_Char_Buf_Subsystem_Char_Buf_DMA configuration
 *
 */

#define ALT_MODULE_CLASS_VGA_Subsystem_Char_Buf_Subsystem_Char_Buf_DMA altera_up_avalon_video_dma_controller
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_CHAR_BUF_DMA_BASE 0xff203030
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_CHAR_BUF_DMA_IRQ -1
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_CHAR_BUF_DMA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_CHAR_BUF_DMA_NAME "/dev/VGA_Subsystem_Char_Buf_Subsystem_Char_Buf_DMA"
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_CHAR_BUF_DMA_SPAN 16
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_CHAR_BUF_DMA_TYPE "altera_up_avalon_video_dma_controller"


/*
 * VGA_Subsystem_Char_Buf_Subsystem_Onchip_SRAM configuration
 *
 */

#define ALT_MODULE_CLASS_VGA_Subsystem_Char_Buf_Subsystem_Onchip_SRAM altera_avalon_onchip_memory2
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_BASE 0x9000000
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_CONTENTS_INFO ""
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_DUAL_PORT 1
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_INIT_CONTENTS_FILE "Computer_System_VGA_Subsystem_Char_Buf_Subsystem_Onchip_SRAM"
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_INIT_MEM_CONTENT 1
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_INSTANCE_ID "NONE"
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_IRQ -1
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_NAME "/dev/VGA_Subsystem_Char_Buf_Subsystem_Onchip_SRAM"
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_RAM_BLOCK_TYPE "AUTO"
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_SINGLE_CLOCK_OP 1
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_SIZE_MULTIPLE 1
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_SIZE_VALUE 8192
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_SPAN 8192
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_TYPE "altera_avalon_onchip_memory2"
#define VGA_SUBSYSTEM_CHAR_BUF_SUBSYSTEM_ONCHIP_SRAM_WRITABLE 1


/*
 * VGA_Subsystem_VGA_Pixel_DMA configuration
 *
 */

#define ALT_MODULE_CLASS_VGA_Subsystem_VGA_Pixel_DMA altera_up_avalon_video_dma_controller
#define VGA_SUBSYSTEM_VGA_PIXEL_DMA_BASE 0xff203020
#define VGA_SUBSYSTEM_VGA_PIXEL_DMA_IRQ -1
#define VGA_SUBSYSTEM_VGA_PIXEL_DMA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define VGA_SUBSYSTEM_VGA_PIXEL_DMA_NAME "/dev/VGA_Subsystem_VGA_Pixel_DMA"
#define VGA_SUBSYSTEM_VGA_PIXEL_DMA_SPAN 16
#define VGA_SUBSYSTEM_VGA_PIXEL_DMA_TYPE "altera_up_avalon_video_dma_controller"


/*
 * VGA_Subsystem_VGA_Pixel_RGB_Resampler configuration
 *
 */

#define ALT_MODULE_CLASS_VGA_Subsystem_VGA_Pixel_RGB_Resampler altera_up_avalon_video_rgb_resampler
#define VGA_SUBSYSTEM_VGA_PIXEL_RGB_RESAMPLER_BASE 0xff203010
#define VGA_SUBSYSTEM_VGA_PIXEL_RGB_RESAMPLER_IRQ -1
#define VGA_SUBSYSTEM_VGA_PIXEL_RGB_RESAMPLER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define VGA_SUBSYSTEM_VGA_PIXEL_RGB_RESAMPLER_NAME "/dev/VGA_Subsystem_VGA_Pixel_RGB_Resampler"
#define VGA_SUBSYSTEM_VGA_PIXEL_RGB_RESAMPLER_SPAN 4
#define VGA_SUBSYSTEM_VGA_PIXEL_RGB_RESAMPLER_TYPE "altera_up_avalon_video_rgb_resampler"


/*
 * Video_In_Subsystem_Video_In_DMA configuration
 *
 */

#define ALT_MODULE_CLASS_Video_In_Subsystem_Video_In_DMA altera_up_avalon_video_dma_controller
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_DMA_BASE 0xff203060
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_DMA_IRQ -1
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_DMA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_DMA_NAME "/dev/Video_In_Subsystem_Video_In_DMA"
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_DMA_SPAN 16
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_DMA_TYPE "altera_up_avalon_video_dma_controller"


/*
 * Video_In_Subsystem_Video_In_Edge_Detection_Subsystem_Edge_Detection_Router_Controller configuration
 *
 */

#define ALT_MODULE_CLASS_Video_In_Subsystem_Video_In_Edge_Detection_Subsystem_Edge_Detection_Router_Controller altera_avalon_pio
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_BASE 0xff203070
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_BIT_CLEARING_EDGE_REGISTER 0
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_BIT_MODIFYING_OUTPUT_REGISTER 0
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_CAPTURE 0
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_DATA_WIDTH 1
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_DO_TEST_BENCH_WIRING 0
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_DRIVEN_SIM_VALUE 0
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_EDGE_TYPE "NONE"
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_FREQ 100000000
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_HAS_IN 0
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_HAS_OUT 1
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_HAS_TRI 0
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_IRQ -1
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_IRQ_TYPE "NONE"
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_NAME "/dev/Video_In_Subsystem_Video_In_Edge_Detection_Subsystem_Edge_Detection_Router_Controller"
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_RESET_VALUE 0
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_SPAN 16
#define VIDEO_IN_SUBSYSTEM_VIDEO_IN_EDGE_DETECTION_SUBSYSTEM_EDGE_DETECTION_ROUTER_CONTROLLER_TYPE "altera_avalon_pio"


/*
 * hal2 configuration
 *
 */

#define ALT_MAX_FD 32
#define ALT_SYS_CLK NIOSVG
#define ALT_TIMESTAMP_CLK NIOSVG
#define INTEL_FPGA_DFL_START_ADDRESS 0xffffffffffffffff
#define INTEL_FPGA_USE_DFL_WALKER 0


/*
 * intel_niosv_g_hal_driver configuration
 *
 */

#define NIOSV_INTERNAL_TIMER_TICKS_PER_SECOND 1000

#endif /* __SYSTEM_H_ */
